In [49]:
#importing Libraries

import pandas as pd # type: ignore
import numpy as np # type: ignore

# Data Acquisition 

In [50]:
#loading data set1

dataset1 = pd.read_excel("C:/Users/vipin/OneDrive/Documents/Desktop/Project2/dataset_1.xlsx")

In [51]:
#printing dataset 1

dataset1

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1 2011-01-01       1   0     1   0    False        6           1   
1          2 2011-01-01       1   0     1   1    False        6           1   
2          3 2011-01-01       1   0     1   2    False        6           1   
3          4 2011-01-01       1   0     1   3    False        6           1   
4          5 2011-01-01       1   0     1   4    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [52]:
#printing top 10 Entries

dataset1.head(10)

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        1 2011-01-01       1   0     1   0    False        6           1   
1        2 2011-01-01       1   0     1   1    False        6           1   
2        3 2011-01-01       1   0     1   2    False        6           1   
3        4 2011-01-01       1   0     1   3    False        6           1   
4        5 2011-01-01       1   0     1   4    False        6           1   
5        6 2011-01-01       1   0     1   5    False        6           2   
6        7 2011-01-01       1   0     1   6    False        6           1   
7        8 2011-01-01       1   0     1   7    False        6           1   
8        9 2011-01-01       1   0     1   8    False        6           1   
9       10 2011-01-01       1   0     1   9    False        6           1   

   temp  
0  0.24  
1  0.22  
2  0.22  
3  0.24  
4  0.24  
5  0.24  
6  0.22  
7  0.20  
8  0.24  
9  0.32

In [53]:
#printing last 10 Entries

dataset1.tail(10)

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
600      601 2011-01-28       1   0     1   6    False        5           2   
601      602 2011-01-28       1   0     1   7    False        5           2   
602      603 2011-01-28       1   0     1   8    False        5           2   
603      604 2011-01-28       1   0     1   9    False        5           3   
604      605 2011-01-28       1   0     1  10    False        5           3   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp  
600  0.18  
601  0.16  
602  0.16  
603  0.18  
604  0.18  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20

In [54]:
#Getting DataType Info

dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   instant     610 non-null    int64         
 1   dteday      610 non-null    datetime64[ns]
 2   season      610 non-null    int64         
 3   yr          610 non-null    int64         
 4   mnth        610 non-null    int64         
 5   hr          610 non-null    int64         
 6   holiday     610 non-null    bool          
 7   weekday     610 non-null    int64         
 8   weathersit  610 non-null    int64         
 9   temp        610 non-null    float64       
dtypes: bool(1), datetime64[ns](1), float64(1), int64(7)
memory usage: 43.6 KB


In [55]:
#Generate descriptive statistics

dataset1.describe()

instant  season     yr   mnth          hr     weekday  weathersit  \
count  610.000000   610.0  610.0  610.0  610.000000  610.000000  610.000000   
mean   305.500000     1.0    0.0    1.0   11.795082    2.977049    1.477049   
std    176.236111     0.0    0.0    0.0    6.852107    2.054943    0.643496   
min      1.000000     1.0    0.0    1.0    0.000000    0.000000    1.000000   
25%    153.250000     1.0    0.0    1.0    6.000000    1.000000    1.000000   
50%    305.500000     1.0    0.0    1.0   12.000000    3.000000    1.000000   
75%    457.750000     1.0    0.0    1.0   18.000000    5.000000    2.000000   
max    610.000000     1.0    0.0    1.0   23.000000    6.000000    4.000000   

             temp  
count  610.000000  
mean     0.196885  
std      0.081304  
min      0.020000  
25%      0.160000  
50%      0.200000  
75%      0.235000  
max      0.460000

In [56]:
#Finding Null Value

dataset1.isnull()

instant  dteday  season     yr   mnth     hr  holiday  weekday  \
0      False   False   False  False  False  False    False    False   
1      False   False   False  False  False  False    False    False   
2      False   False   False  False  False  False    False    False   
3      False   False   False  False  False  False    False    False   
4      False   False   False  False  False  False    False    False   
..       ...     ...     ...    ...    ...    ...      ...      ...   
605    False   False   False  False  False  False    False    False   
606    False   False   False  False  False  False    False    False   
607    False   False   False  False  False  False    False    False   
608    False   False   False  False  False  False    False    False   
609    False   False   False  False  False  False    False    False   

     weathersit   temp  
0         False  False  
1         False  False  
2         False  False  
3         False  False  
4         False  False  
..          ...    ...  
605       False  False  
606       False  False  
607       False  False  
608       False  False  
609       False  False  

[610 rows x 10 columns]

In [57]:
#Summing of Null Value

dataset1.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [58]:
#load dataset 2

dataset2 = pd.read_excel("C:/Users/vipin/OneDrive/Documents/Desktop/Project2/dataset_2.xlsx") 

In [59]:
#printing dataset 2

dataset2

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [60]:
#printing top 5 Entries

dataset2.head()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0           0        1  0.2879  0.81        0.0       3          13   16
1           1        2  0.2727  0.80        0.0       8          32   40
2           2        3  0.2727  0.80        0.0       5          27   32
3           3        4  0.2879  0.75        0.0       3          10   13
4           4        5  0.2879  0.75        0.0       0           1    1

In [61]:
#printing last 5 Entries

dataset2.tail()

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

In [62]:
#Getting DataType Info

dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  610 non-null    int64  
 1   instant     610 non-null    int64  
 2   atemp       599 non-null    float64
 3   hum         610 non-null    float64
 4   windspeed   610 non-null    float64
 5   casual      610 non-null    int64  
 6   registered  610 non-null    int64  
 7   cnt         610 non-null    int64  
dtypes: float64(3), int64(5)
memory usage: 38.2 KB


In [63]:
#Generate descriptive statistics

dataset2.describe()

Unnamed: 0     instant       atemp         hum   windspeed      casual  \
count  610.000000  610.000000  599.000000  610.000000  610.000000  610.000000   
mean   304.500000  305.500000    0.199935    0.562475    0.204851    4.501639   
std    176.236111  176.236111    0.078836    0.175440    0.121806    6.319945   
min      0.000000    1.000000    0.000000    0.210000    0.000000    0.000000   
25%    152.250000  153.250000    0.151500    0.432500    0.104500    0.000000   
50%    304.500000  305.500000    0.197000    0.520000    0.194000    2.000000   
75%    456.750000  457.750000    0.242400    0.690000    0.283600    6.000000   
max    609.000000  610.000000    0.454500    1.000000    0.582100   47.000000   

       registered         cnt  
count  610.000000  610.000000  
mean    51.068852   55.570492  
std     47.021204   49.316802  
min      0.000000    1.000000  
25%     14.000000   16.000000  
50%     43.000000   47.000000  
75%     70.000000   79.750000  
max    247.000000  249.000000

In [64]:
#Finding Null Value

dataset2.isnull()

Unnamed: 0  instant  atemp    hum  windspeed  casual  registered    cnt
0         False    False  False  False      False   False       False  False
1         False    False  False  False      False   False       False  False
2         False    False  False  False      False   False       False  False
3         False    False  False  False      False   False       False  False
4         False    False  False  False      False   False       False  False
..          ...      ...    ...    ...        ...     ...         ...    ...
605       False    False  False  False      False   False       False  False
606       False    False  False  False      False   False       False  False
607       False    False  False  False      False   False       False  False
608       False    False  False  False      False   False       False  False
609       False    False  False  False      False   False       False  False

[610 rows x 8 columns]

In [65]:
#Summing of Null Value

dataset2.isnull().sum()

Unnamed: 0     0
instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [66]:
# Join the datasets using the merge function

Final = pd.merge(dataset1, dataset2, how='inner')

In [67]:
# Save the final dataframe as a CSV file
Final.to_csv('Final.csv', index=False)

# Display the final dataframe
Final

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1 2011-01-01       1   0     1   0    False        6           1   
1          2 2011-01-01       1   0     1   1    False        6           1   
2          3 2011-01-01       1   0     1   2    False        6           1   
3          4 2011-01-01       1   0     1   3    False        6           1   
4          5 2011-01-01       1   0     1   4    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp  Unnamed: 0   atemp   hum  windspeed  casual  registered  cnt  
0    0.24           0  0.2879  0.81     0.0000       3          13   16  
1    0.22           1  0.2727  0.80     0.0000       8          32   40  
2    0.22           2  0.2727  0.80     0.0000       5          27   32  
3    0.24           3  0.2879  0.75     0.0000       3          10   13  
4    0.24           4  0.2879  0.75     0.0000       0           1    1  
..    ...         ...     ...   ...        ...     ...         ...  ...  
605  0.18         605  0.2121  0.93     0.1045       0          30   30  
606  0.18         606  0.2121  0.93     0.1045       1          28   29  
607  0.18         607  0.2121  0.93     0.1045       0          31   31  
608  0.22         608  0.2727  0.80     0.0000       2          36   38  
609  0.20         609  0.2576  0.86     0.0000       1          40   41  

[610 rows x 17 columns]

In [68]:
# Drop Unnamed columns

columns_to_drop = ['Unnamed: 0']
Final1 = Final.drop(columns=columns_to_drop, axis=1)

Final1

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1 2011-01-01       1   0     1   0    False        6           1   
1          2 2011-01-01       1   0     1   1    False        6           1   
2          3 2011-01-01       1   0     1   2    False        6           1   
3          4 2011-01-01       1   0     1   3    False        6           1   
4          5 2011-01-01       1   0     1   4    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp   atemp   hum  windspeed  casual  registered  cnt  
0    0.24  0.2879  0.81     0.0000       3          13   16  
1    0.22  0.2727  0.80     0.0000       8          32   40  
2    0.22  0.2727  0.80     0.0000       5          27   32  
3    0.24  0.2879  0.75     0.0000       3          10   13  
4    0.24  0.2879  0.75     0.0000       0           1    1  
..    ...     ...   ...        ...     ...         ...  ...  
605  0.18  0.2121  0.93     0.1045       0          30   30  
606  0.18  0.2121  0.93     0.1045       1          28   29  
607  0.18  0.2121  0.93     0.1045       0          31   31  
608  0.22  0.2727  0.80     0.0000       2          36   38  
609  0.20  0.2576  0.86     0.0000       1          40   41  

[610 rows x 16 columns]

In [69]:
#final column name

Final1.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual',
       'registered', 'cnt'],
      dtype='object')

In [70]:
#dimensions of data 
Final1.shape

(610, 16)

# Data Wrangling

Finding Unique Value

In [71]:
unique_instant = Final1['instant'].unique()
unique_instant

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [72]:
unique_dteday = Final1['dteday'].unique()
unique_dteday

array(['2011-01-01T00:00:00.000000000', '2011-01-02T00:00:00.000000000',
       '2011-01-03T00:00:00.000000000', '2011-01-04T00:00:00.000000000',
       '2011-01-05T00:00:00.000000000', '2011-01-06T00:00:00.000000000',
       '2011-01-07T00:00:00.000000000', '2011-01-08T00:00:00.000000000',
       '2011-01-09T00:00:00.000000000', '2011-01-10T00:00:00.000000000',
       '2011-01-11T00:00:00.000000000', '2011-01-12T00:00:00.000000000',
       '2011-01-13T00:00:00.000000000', '2011-01-14T00:00:00.000000000',
       '2011-01-15T00:00:00.000000000', '2011-01-16T00:00:00.000000000',
       '2011-01-17T00:00:00.000000000', '2011-01-18T00:00:00.000000000',
       '2011-01-19T00:00:00.000000000', '2011-01-20T00:00:00.000000000',
       '2011-01-21T00:00:00.000000000', '2011-01-22T00:00:00.000000000',
       '2011-01-23T00:00:00.000000000', '2011-01-24T00:00:00.000000000',
       '2011-01-25T00:00:00.000000000', '2011-01-26T00:00:00.000000000',
       '2011-01-27T00:00:00.000000000', '2011-01-28

In [73]:
unique_seasons = Final1['season'].unique()
unique_seasons

array([1], dtype=int64)

In [74]:
unique_year = Final1['yr'].unique()
unique_year

array([0], dtype=int64)

In [75]:
unique_mnth = Final1['mnth'].unique()
unique_mnth

array([1], dtype=int64)

In [76]:
unique_hr = Final1['hr'].unique()
unique_hr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int64)

In [77]:
unique_holidays = Final1['holiday'].unique()
unique_holidays

array([False,  True])

In [78]:
unique_weekday = Final1['weekday'].unique()
unique_weekday

array([6, 0, 1, 2, 3, 4, 5], dtype=int64)

In [79]:
unique_weathersit = Final1['weathersit'].unique()
unique_weathersit

array([1, 2, 3, 4], dtype=int64)

In [80]:
unique_temp = Final1['temp'].unique()
unique_temp

array([0.24, 0.22, 0.2 , 0.32, 0.38, 0.36, 0.42, 0.46, 0.44, 0.4 , 0.34,
       0.3 , 0.26, 0.16, 0.14, 0.18, 0.12, 0.28, 0.1 , 0.08, 0.06, 0.04,
       0.02])

In [81]:
unique_atemp = Final1['atemp'].unique()
unique_atemp

array([0.2879, 0.2727, 0.2576,    nan, 0.3485, 0.3939, 0.3333, 0.4242,
       0.4545, 0.4394, 0.4091, 0.2273, 0.2121, 0.197 , 0.1364, 0.1061,
       0.1212, 0.1667, 0.1818, 0.2424, 0.1515, 0.3182, 0.0606, 0.0758,
       0.0909, 0.303 , 0.0303, 0.0455, 0.    , 0.0152])

In [82]:
unique_hum = Final1['hum'].unique()
unique_hum

array([0.81, 0.8 , 0.75, 0.86, 0.76, 0.77, 0.72, 0.82, 0.88, 0.87, 0.94,
       1.  , 0.71, 0.66, 0.57, 0.46, 0.42, 0.39, 0.44, 0.47, 0.5 , 0.43,
       0.4 , 0.35, 0.3 , 0.32, 0.64, 0.69, 0.55, 0.59, 0.63, 0.68, 0.74,
       0.51, 0.56, 0.52, 0.49, 0.48, 0.37, 0.33, 0.28, 0.38, 0.36, 0.93,
       0.29, 0.53, 0.34, 0.54, 0.41, 0.45, 0.92, 0.62, 0.58, 0.61, 0.6 ,
       0.65, 0.7 , 0.27, 0.21, 0.25, 0.26])

In [83]:
unique_ws = Final1['windspeed'].unique()
unique_ws

array([0.    , 0.0896, 0.2537, 0.2836, 0.2985, 0.194 , 0.2239, 0.1343,
       0.1642, 0.3284, 0.4478, 0.3582, 0.4179, 0.3881, 0.1045, 0.4925,
       0.5522, 0.4627, 0.5224, 0.5821])

In [84]:
unique_casual = Final1['casual'].unique()
unique_casual

array([ 3,  8,  5,  0,  2,  1, 12, 26, 29, 47, 35, 40, 41, 15,  9,  6, 11,
        4,  7, 16, 20, 19, 10, 13, 14, 18, 17, 21, 33, 23, 22, 24],
      dtype=int64)

In [85]:
unique_registered = Final1['registered'].unique()
unique_registered

array([ 13,  32,  27,  10,   1,   0,   2,   7,   6,  24,  30,  55,  47,
        71,  70,  52,  26,  31,  25,  17,  16,   8,   4,  19,  46,  54,
        73,  64,  67,  58,  43,  29,  20,   9,   5,   3,  63, 153,  81,
        33,  41,  48,  53,  66, 146, 148, 102,  49,  11,  36,  92, 177,
        98,  37,  50,  79,  68, 202, 179, 110,  34,  87, 192, 109,  74,
        65,  85, 186, 166, 127,  82,  40,  18,  95, 216, 116,  42,  57,
        78,  59, 163, 158,  51,  76, 190, 125, 178,  39,  14,  15,  56,
        60,  90,  83,  69,  28,  35,  22,  12,  77,  44,  38,  75, 184,
       174, 154,  97, 214,  45,  72, 130,  94, 139, 135, 197, 137, 141,
       156, 117, 155, 134,  89,  80, 108,  61, 124, 132, 196, 107, 100,
       247, 140,  86,  62, 207, 210, 159, 151, 119,  93,  23, 171, 145,
       101,  21, 103, 233, 208, 218, 133], dtype=int64)

In [86]:
unique_cnt = Final1['cnt'].unique()
unique_cnt

array([ 16,  40,  32,  13,   1,   2,   3,   8,  14,  36,  56,  84,  94,
       106, 110,  93,  67,  35,  37,  34,  28,  39,  17,   9,   6,  20,
        53,  70,  75,  59,  74,  76,  65,  30,  22,  31,   5,  64, 154,
        88,  44,  51,  61,  77,  72, 157,  52,  12,   4, 179, 100,  42,
        57,  78,  97,  63,  83, 212, 182, 112,  54,  48,  11,  33, 195,
       115,  46,  79,  71,  62,  89, 190, 169, 132,  43,  19,  95, 219,
       122,  45,  86, 172, 163,  69,  23,   7, 210, 134,  73,  50,  87,
       187, 123,  15,  25,  98, 102,  55,  10,  49,  82,  92,  41,  38,
       188,  47, 178, 155,  24,  18,  27,  99, 217, 130, 136,  29, 128,
        81,  68, 139, 137, 202,  60, 162, 144, 158, 117,  90, 159, 101,
       118, 129,  26, 104,  91, 113, 105,  21,  80, 125, 133, 197, 109,
       161, 249, 143, 215, 185, 152, 126, 166, 120,  96, 103,  58, 116,
       177, 184, 153, 108, 238, 222, 225, 146, 119], dtype=int64)

In [87]:
#second way to find the unique values of multiple column

# List of columns
count = ['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
                    'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

# Dictionary for storing counts
unique_counts = {}

# Counting unique values for each column
for column in count:
    unique_counts[column] = Final1[column].nunique()

# Print counts
for column, count in unique_counts.items():
    print(f"Column '{column}': {count} unique values")


Column 'instant': 610 unique values
Column 'dteday': 28 unique values
Column 'season': 1 unique values
Column 'yr': 1 unique values
Column 'mnth': 1 unique values
Column 'hr': 24 unique values
Column 'holiday': 2 unique values
Column 'weekday': 7 unique values
Column 'weathersit': 4 unique values
Column 'temp': 23 unique values
Column 'atemp': 29 unique values
Column 'hum': 61 unique values
Column 'windspeed': 20 unique values
Column 'casual': 32 unique values
Column 'registered': 150 unique values
Column 'cnt': 165 unique values


In [88]:
#checking datatype

Final1.dtypes

instant                int64
dteday        datetime64[ns]
season                 int64
yr                     int64
mnth                   int64
hr                     int64
holiday                 bool
weekday                int64
weathersit             int64
temp                 float64
atemp                float64
hum                  float64
windspeed            float64
casual                 int64
registered             int64
cnt                    int64
dtype: object

In [89]:
#checking missing values 

Final1.isnull().sum()

instant        0
dteday         0
season         0
yr             0
mnth           0
hr             0
holiday        0
weekday        0
weathersit     0
temp           0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

#Finding missing values

In [90]:
Final1.fillna(Final1.mean(numeric_only=True), inplace=True)

In [91]:
Final1.fillna(Final1.median(numeric_only=True), inplace=True)

In [92]:
Final1.fillna(Final1.mode(), inplace=True)

In [93]:
#Checking final Missing values if any 

Final1.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [94]:
#summary statistics

Final1.describe()

instant  season     yr   mnth          hr     weekday  weathersit  \
count  610.000000   610.0  610.0  610.0  610.000000  610.000000  610.000000   
mean   305.500000     1.0    0.0    1.0   11.795082    2.977049    1.477049   
std    176.236111     0.0    0.0    0.0    6.852107    2.054943    0.643496   
min      1.000000     1.0    0.0    1.0    0.000000    0.000000    1.000000   
25%    153.250000     1.0    0.0    1.0    6.000000    1.000000    1.000000   
50%    305.500000     1.0    0.0    1.0   12.000000    3.000000    1.000000   
75%    457.750000     1.0    0.0    1.0   18.000000    5.000000    2.000000   
max    610.000000     1.0    0.0    1.0   23.000000    6.000000    4.000000   

             temp       atemp         hum   windspeed      casual  registered  \
count  610.000000  610.000000  610.000000  610.000000  610.000000  610.000000   
mean     0.196885    0.199935    0.562475    0.204851    4.501639   51.068852   
std      0.081304    0.078120    0.175440    0.121806    6.319945   47.021204   
min      0.020000    0.000000    0.210000    0.000000    0.000000    0.000000   
25%      0.160000    0.151500    0.432500    0.104500    0.000000   14.000000   
50%      0.200000    0.197000    0.520000    0.194000    2.000000   43.000000   
75%      0.235000    0.227300    0.690000    0.283600    6.000000   70.000000   
max      0.460000    0.454500    1.000000    0.582100   47.000000  247.000000   

              cnt  
count  610.000000  
mean    55.570492  
std     49.316802  
min      1.000000  
25%     16.000000  
50%     47.000000  
75%     79.750000  
max    249.000000

# Conclusion

In [95]:


print("The dataset appears to be relatively clean and well-structured, with no missing values after filling them.")

print("The unique values for each column seem reasonable, indicating no obvious inconsistencies or errors.")

print("Summary statistics provide insights into the distribution and range of values for numerical columns.")

print("Further analysis and modeling can be performed on the cleaned dataset for insights and predictions.")


The dataset appears to be relatively clean and well-structured, with no missing values after filling them.
The unique values for each column seem reasonable, indicating no obvious inconsistencies or errors.
Summary statistics provide insights into the distribution and range of values for numerical columns.
Further analysis and modeling can be performed on the cleaned dataset for insights and predictions.
